services:
  - type: web
    name: express-api
    runtime: node
    plan: starter
    region: oregon
    branch: main

    buildCommand: npm run build
    startCommand: node dist/server.js

    autoDeploy: true
